### ISSUE TITLE
Failing to add Homebridge

### ISSUE THREAD

**Issue by chrisremie** [mozilla-iot/homekit-adapter#18]
[I'm new to this, and I'm not a programmer]

I'm trying to add Homebridge
When I do this in AddOns>Settings>Homekit>Configure
I get this error:

```
2018-12-03 12:13:00.359 INFO   : Loading add-on: homekit-adapter
2018-12-03 12:13:03.826 INFO   : homekit: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2018-12-03 12:13:04.014 INFO   : homekit: Loading add-on for homekit-adapter from /home/pi/.mozilla-iot/addons/homekit-adapter
2018-12-03 12:13:13.586 INFO   : homekit: Found IP device: { name: 'Homebridge-CAD8',
2018-12-03 12:13:13.607 INFO   : homekit:   address: '192.168.1.191',
2018-12-03 12:13:13.618 INFO   : homekit:   port: 51826,
2018-12-03 12:13:13.631 INFO   : homekit:   'c#': 4,
2018-12-03 12:13:13.641 INFO   : homekit:   ff: 0,
2018-12-03 12:13:13.651 INFO   : homekit:   id: 'CC:22:3D:E3:CE:30',
2018-12-03 12:13:13.661 INFO   : homekit:   md: 'Homebridge',
2018-12-03 12:13:13.670 INFO   : homekit:   pv: '1.0',
2018-12-03 12:13:13.679 INFO   : homekit:   's#': 1,
2018-12-03 12:13:13.692 INFO   : homekit:   sf: 0,
2018-12-03 12:13:13.702 INFO   : homekit:   ci: 2 }
2018-12-03 12:13:13.728 INFO   : homekit: Error loading device CC:22:3D:E3:CE:30: Key not found
2018-12-03 12:13:13.874 INFO   : homekit: Pairing failed for device CC:22:3D:E3:CE:30: TypeError: Cannot read property '0' of undefined
2018-12-03 12:13:13.889 INFO   : homekit: Pairing failed for device CC:22:3D:E3:CE:30: TypeError: Cannot read property '0' of undefined
```

When I try it with Add Things, I get this error:
Incorrect PIN in the web UI (not true)

and this output:

```
2018-12-03 12:14:29.486 INFO   : Opened a new things socket
2018-12-03 12:14:29.512 INFO   : About to call startPairing on HomeKitAdapter
2018-12-03 12:14:29.556 INFO   : homekit: Adapter: HomeKitAdapter id homekit-adapter pairing started
2018-12-03 12:14:55.511 INFO   : AdapterProxy: setPin: 031-45-154 for: homekit-CC:22:3D:E3:CE:30
2018-12-03 12:14:55.563 INFO   : homekit: Pairing failed for device CC:22:3D:E3:CE:30: TypeError: Cannot read property '0' of undefined
2018-12-03 12:14:55.576 ERROR  : homekit: AddonManagerProxy: Failed to set PIN for device homekit-CC:22:3D:E3:CE:30
2018-12-03 12:14:55.588 ERROR  : homekit: TypeError: Cannot read property '0' of undefined
2018-12-03 12:14:55.593 ERROR  : homekit:     at Promise (/home/pi/.mozilla-iot/addons/homekit-adapter/node_modules/hap-controller/lib/protocol/pairing-protocol.js:186:36)
2018-12-03 12:14:55.598 ERROR  : homekit:     at new Promise (<anonymous>)
2018-12-03 12:14:55.602 ERROR  : homekit:     at PairingProtocol.parsePairSetupM2 (/home/pi/.mozilla-iot/addons/homekit-adapter/node_modules/hap-controller/lib/protocol/pairing-protocol.js:178:12)
2018-12-03 12:14:55.607 ERROR  : homekit:     at pairingProtocol.buildPairSetupM1.then.then (/home/pi/.mozilla-iot/addons/homekit-adapter/node_modules/hap-controller/lib/transport/ip/http-client.js:77:35)
2018-12-03 12:14:55.614 ERROR  : homekit:     at <anonymous>
2018-12-03 12:14:55.619 ERROR  : homekit:     at process._tickCallback (internal/process/next_tick.js:189:7)
2018-12-03 12:14:55.629 ERROR  : Failed to set PIN for homekit-CC:22:3D:E3:CE:30: undefined
2018-12-03 12:15:29.521 INFO   : Pairing timeout
2018-12-03 12:15:29.528 ERROR  : Thing was not added
2018-12-03 12:15:29.532 ERROR  : addNewThing cancelled
2018-12-03 12:15:29.543 INFO   : homekit: Adapter: HomeKitAdapter id homekit-adapter pairing cancelled
```

**Comment by mrstegeman** [comment]
I was getting the same error with a previously paired Homebridge setup, but after removing `~/.homebridge`, pairing worked fine.

If you have Homebridge paired with another device, you cannot pair it with the gateway.
