### ISSUE TITLE
Homekit adapter in permanent crash looop after upgrade to 0.5.0 

### ISSUE THREAD

**Issue by plackettsj1** [mozilla-iot/homekit-adapter#38]
Hi
I have a couple of RPI running Mozilla-IOT 0.9.2 with homekit 0.5.0
I have 6 EVE window / door sensors - none of them now gets a change to update as the following repeating code is found on all my servers:
2019-09-22 09:57:36.542 INFO   : homekit: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3 
2019-09-22 09:57:36.584 INFO   : homekit: Loading add-on for homekit-adapter from /home/pi/.mozilla-iot/addons/homekit-adapter 
2019-09-22 09:57:38.657 INFO   : homekit: Found BLE device: { CoID: 76,
2019-09-22 09:57:38.659 INFO   : homekit:   TY: 6,
2019-09-22 09:57:38.660 INFO   : homekit:   AIL: 49,
2019-09-22 09:57:38.662 INFO   : homekit:   SF: 0,
2019-09-22 09:57:38.664 INFO   : homekit:   DeviceID: '5b:42:c9:a0:2a:45',
2019-09-22 09:57:38.666 INFO   : homekit:   ACID: 10,
2019-09-22 09:57:38.667 INFO   : homekit:   GSN: 13411,
2019-09-22 09:57:38.669 INFO   : homekit:   CN: 1,
2019-09-22 09:57:38.670 INFO   : homekit:   CV: 2 }
2019-09-22 09:57:38.673 ERROR  : homekit: /home/pi/.mozilla-iot/addons/homekit-adapter/lib/homekit-adapter.js:193
2019-09-22 09:57:38.674 ERROR  : homekit:       device.promise.then(() => {
2019-09-22 09:57:38.675 ERROR  : homekit:                      ^
2019-09-22 09:57:38.676 ERROR  : homekit:
2019-09-22 09:57:38.678 ERROR  : homekit: TypeError: Cannot read property 'then' of undefined
2019-09-22 09:57:38.679 ERROR  : homekit:     at HomeKitAdapter.addBLEDevice (/home/pi/.mozilla-iot/addons/homekit-adapter/lib/homekit-adapter.js:193:22)
2019-09-22 09:57:38.680 ERROR  : homekit:     at BLEDiscovery.bleDiscovery.on (/home/pi/.mozilla-iot/addons/homekit-adapter/lib/homekit-adapter.js:223:12)
2019-09-22 09:57:38.681 ERROR  : homekit:     at emitOne (events.js:116:13)
2019-09-22 09:57:38.682 ERROR  : homekit:     at BLEDiscovery.emit (events.js:211:7)
2019-09-22 09:57:38.683 ERROR  : homekit:     at BLEDiscovery._handleDiscover (/home/pi/.mozilla-iot/addons/homekit-adapter/node_modules/hap-controller/lib/transport/ble/ble-discovery.js:109:10)
2019-09-22 09:57:38.684 ERROR  : homekit:     at emitOne (events.js:116:13)
2019-09-22 09:57:38.685 ERROR  : homekit:     at Noble.emit (events.js:211:7)
2019-09-22 09:57:38.686 ERROR  : homekit:     at Noble.onDiscover (/home/pi/.mozilla-iot/addons/homekit-adapter/node_modules/@abandonware/noble/lib/noble.js:178:10)
2019-09-22 09:57:38.687 ERROR  : homekit:     at emitMany (events.js:147:13)
2019-09-22 09:57:38.688 ERROR  : homekit:     at NobleBindings.emit (events.js:224:7)
2019-09-22 09:57:38.691 INFO   : Plugin: homekit-adapter died, code = 1 restarting after 20000

Can anyone help me please as they are all useless at the moment.

I have tried this with buster and jessie and get the same error, and I have done a completely new install and this also failed.

I have also tried with internal and external bluetooth adapters. 

The only way to get homekit to start is to disable all bluetooth which does defeat the object of monitoring BLE devices :-)

**Comment by plackettsj1** [comment]
I suspect the problem is that some of the devices are already paired on another gateway - I have an old house and one gateway won't cover all three floors. The DeviceID in the error message can be different at each restart, but the set is finite. I think, but the logs are over-written, that the error message was there in previous versions but that it did not cause homekit to crash.
Thanks again
Simon

**Comment by sotomski** [comment]
Same here. I've disabled on-board WiFi on my RPi3 and now the above crash loop happens. 
I've tried pairing with Eve Room 1st Gen after hard resetting and removing it from Home-Kit on my phone.

```
2019-09-22 11:32:14.488 INFO   : Plugin: homekit-adapter died, code = 1 restarting after 7000
2019-09-22 11:32:22.258 INFO   : homekit: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2019-09-22 11:32:22.305 INFO   : homekit: Loading add-on for homekit-adapter from /home/pi/.mozilla-iot/addons/homekit-adapter
2019-09-22 11:32:24.464 INFO   : homekit: Found BLE device: { CoID: 76,
2019-09-22 11:32:24.466 INFO   : homekit:   TY: 6,
2019-09-22 11:32:24.468 INFO   : homekit:   AIL: 49,
2019-09-22 11:32:24.469 INFO   : homekit:   SF: 0,
2019-09-22 11:32:24.471 INFO   : homekit:   DeviceID: '34:04:e0:ac:9d:30',
2019-09-22 11:32:24.472 INFO   : homekit:   ACID: 7,
2019-09-22 11:32:24.474 INFO   : homekit:   GSN: 14,
2019-09-22 11:32:24.475 INFO   : homekit:   CN: 2,
2019-09-22 11:32:24.476 INFO   : homekit:   CV: 2 }
2019-09-22 11:32:24.484 ERROR  : homekit: /home/pi/.mozilla-iot/addons/homekit-adapter/lib/homekit-adapter.js:193
2019-09-22 11:32:24.485 ERROR  : homekit:       device.promise.then(() => {
2019-09-22 11:32:24.487 ERROR  : homekit:                      ^
2019-09-22 11:32:24.488 ERROR  : homekit: 
2019-09-22 11:32:24.490 ERROR  : homekit: TypeError: Cannot read property 'then' of undefined
2019-09-22 11:32:24.492 ERROR  : homekit:     at HomeKitAdapter.addBLEDevice (/home/pi/.mozilla-iot/addons/homekit-adapter/lib/homekit-adapter.js:193:22)
2019-09-22 11:32:24.493 ERROR  : homekit:     at BLEDiscovery.bleDiscovery.on (/home/pi/.mozilla-iot/addons/homekit-adapter/lib/homekit-adapter.js:223:12)
2019-09-22 11:32:24.495 ERROR  : homekit:     at emitOne (events.js:116:13)
2019-09-22 11:32:24.496 ERROR  : homekit:     at BLEDiscovery.emit (events.js:211:7)
2019-09-22 11:32:24.497 ERROR  : homekit:     at BLEDiscovery._handleDiscover (/home/pi/.mozilla-iot/addons/homekit-adapter/node_modules/hap-controller/lib/transport/ble/ble-discovery.js:109:10)
2019-09-22 11:32:24.499 ERROR  : homekit:     at emitOne (events.js:116:13)
2019-09-22 11:32:24.500 ERROR  : homekit:     at Noble.emit (events.js:211:7)
2019-09-22 11:32:24.501 ERROR  : homekit:     at Noble.onDiscover (/home/pi/.mozilla-iot/addons/homekit-adapter/node_modules/@abandonware/noble/lib/noble.js:178:10)
2019-09-22 11:32:24.502 ERROR  : homekit:     at emitMany (events.js:147:13)
2019-09-22 11:32:24.504 ERROR  : homekit:     at NobleBindings.emit (events.js:224:7)
2019-09-22 11:32:24.508 INFO   : Plugin: homekit-adapter died, code = 1 restarting after 8000
```

**Comment by mrstegeman** [comment]
Sorry about this. Fixed in v0.5.1.

**Comment by plackettsj1** [comment]
no probs - thanks for the fast response
Will 5.1 be released with Gateway 10 or is it earlier??

Thanks
Simon

**Comment by plackettsj1** [comment]
Hi Michael - I have everything stable again - however I can not persuade
any of my existing gateways to pair a new EVE Door Sensor device.
I can persuade a new gateway, after fresh install, to pair a new device but
after re-booting either the mozilla-iot-gateway or the pi - they are never
again recognised as EVE sensors, they stop at being Custom Things.  More
details below.

I have tried the following combinations, all with the latest software
Gateway 0.9.2 and Homekit 0.7.1
1) Stretch with on-board bluetooth
2) Stretch with USB bluetooth
3) Buster with on-board bluetooth on RPI 3
4) Buster with USB bluetooth on RPI3
5) Buster with on-board Bluetooth on RPI4
6) Buster with USB Bluetooth on RPI4

they all behave the same way which is

1) Where there is a virgin install of IOT it is possible to get one device
paired - to do this you have to have the EVE door sensor powered off with
the battery out, and start the gateway. Once the gateway is up, start the
pairing process and then put the battery back into the EVE sensor. At this
point you can add the pin and it works.... just once..... After restarting
the gateway the device is never recognised as en EVE sensor again - the
software never finds the service that is associated with the device - so it
remains as a generic "Custom Thing" with no properties.

2) On any gateway that has any previously installed EVE Sensors I am unable
to add any new ones. The pairing times out - and I have tried endless
combinations of resetting the EVE sensor - battery in and out, at various
points in the process, after having rebooted mozilla-iot-gateway with
systemctl or the entire pi.

I am sending a couple of logs with this email - one from gateway5 which has
existing devices and one from gateway1 which I install afresh.

In the fresh install I have left the portion that shows the initial pairing
successful and then the failures of subsequent devices.
For the gateway5 I have left couple of re-boots in and all the pairings
fail.

If I can help with the testing of any of this I would be delighted to as I
now have a significant investment in EVE sensors :-)
My node isn't good enough to help with the coding :-(

Thank-you for any help.

Simon

**Comment by mrstegeman** [comment]
For anybody reading, there's more discussion in #43.
